/* Service worker — offline support.
   Generated by build.sh; do not edit sw.js at the repo root directly.
   Source template: _partials/sw.js  ·  Version is a content hash, so a rebuild
   invalidates the old cache automatically. */

var VERSION = '2689b59e7459';
var CACHE = 'calisthenics-' + VERSION;
var ASSETS = [
  'exercises.html',
  'faq.html',
  'fundamentals.html',
  'gear.html',
  'goals.html',
  'index.html',
  'nutrition.html',
  'program.html',
  'recovery.html',
  'search.html',
  'tracker.html',
  'assets/style.css',
  'assets/site.js',
  'assets/search-index.json',
  'assets/images/discipline-hero.jpg',
  'assets/images/workout-onramp-legs.webp',
  'assets/images/workout-onramp-pull.webp',
  'assets/images/workout-onramp-push.webp'
];

self.addEventListener('install', function (e) {
  e.waitUntil(
    caches.open(CACHE)
      .then(function (c) { return c.addAll(ASSETS); })
      .then(function () { return self.skipWaiting(); })
  );
});

self.addEventListener('activate', function (e) {
  e.waitUntil(
    caches.keys()
      .then(function (keys) {
        return Promise.all(keys.map(function (k) {
          if (k !== CACHE && k.indexOf('calisthenics-') === 0) return caches.delete(k);
        }));
      })
      .then(function () { return self.clients.claim(); })
  );
});

function putInCache(req, res) {
  if (res && res.ok && res.type === 'basic') {
    var copy = res.clone();
    caches.open(CACHE).then(function (c) { c.put(req, copy); });
  }
  return res;
}

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;

  var url;
  try { url = new URL(req.url); } catch (err) { return; }
  if (url.origin !== self.location.origin) return;

  /* Pages: network first, so a rebuild shows up immediately when online,
     and the cached copy carries you when it doesn't. */
  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req)
        .then(function (res) { return putInCache(req, res); })
        .catch(function () {
          return caches.match(req).then(function (r) {
            return r || caches.match('index.html');
          });
        })
    );
    return;
  }

  /* Everything else: cache first — assets are content-hashed by the build. */
  e.respondWith(
    caches.match(req).then(function (r) {
      if (r) return r;
      return fetch(req).then(function (res) { return putInCache(req, res); });
    })
  );
});

/* Lets the page ask which version it is running, for the About box. */
self.addEventListener('message', function (e) {
  if (e.data === 'version' && e.source) e.source.postMessage({ version: VERSION });
});
