/* Service worker — offline support.
   Generated by build.sh; do not edit sw.js at the repo root directly.
   Source template: _partials/sw.js  ·  Version is a content hash, so a rebuild
   invalidates the old cache automatically. */

var VERSION = '{{VERSION}}';
var CACHE = 'calisthenics-' + VERSION;
/* Required: the site is broken offline without these. If any one fails to
   fetch, install fails and the old cache is kept — which is the right outcome. */
var SHELL = [
{{SHELL}}
];

/* Best effort: images and other heavy extras. Cached opportunistically so one
   missing file can never break the install. They are also cached on first view
   by the fetch handler below. */
var EXTRAS = [
{{EXTRAS}}
];

self.addEventListener('install', function (e) {
  e.waitUntil(
    caches.open(CACHE)
      .then(function (c) {
        return c.addAll(SHELL).then(function () {
          return Promise.all(EXTRAS.map(function (u) {
            return c.add(u).catch(function () { /* non-fatal */ });
          }));
        });
      })
      .then(function () { return self.skipWaiting(); })
  );
});

self.addEventListener('activate', function (e) {
  e.waitUntil(
    caches.keys()
      .then(function (keys) {
        return Promise.all(keys.map(function (k) {
          if (k !== CACHE && k.indexOf('calisthenics-') === 0) return caches.delete(k);
        }));
      })
      .then(function () { return self.clients.claim(); })
  );
});

function putInCache(req, res) {
  if (res && res.ok && res.type === 'basic') {
    var copy = res.clone();
    caches.open(CACHE).then(function (c) { c.put(req, copy); });
  }
  return res;
}

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;

  var url;
  try { url = new URL(req.url); } catch (err) { return; }
  if (url.origin !== self.location.origin) return;

  /* Pages: network first, so a rebuild shows up immediately when online,
     and the cached copy carries you when it doesn't. */
  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req)
        .then(function (res) { return putInCache(req, res); })
        .catch(function () {
          return caches.match(req).then(function (r) {
            return r || caches.match('index.html');
          });
        })
    );
    return;
  }

  /* Everything else: cache first — assets are content-hashed by the build. */
  e.respondWith(
    caches.match(req).then(function (r) {
      if (r) return r;
      return fetch(req).then(function (res) { return putInCache(req, res); });
    })
  );
});

/* Lets the page ask which version it is running, for the About box. */
self.addEventListener('message', function (e) {
  if (e.data === 'version' && e.source) e.source.postMessage({ version: VERSION });
});
